'use client';
import React, { useState, useEffect, useMemo } from 'react';
import AppLayout from '../AppLayout';
import RiskBadge from '../components/RiskBadge';
import { LoadingSkeleton, ErrorBanner } from '../components/StateViews';
import { api } from '../../services/api';
import {
  GitBranch,
  ArrowDown,
  Droplets,
  Radio,
  Clock,
  AlertTriangle,
  CheckCircle,
} from 'lucide-react';

// Topological upstream to downstream routing path in the Cauvery Basin
const ROUTING_NODES_CONFIG = [
  {
    id: 'KABINI',
    name: 'Kabini Reservoir',
    type: 'reservoir',
    reach: 'Upper Tributary',
    travel_hrs: 0,
    desc: 'Western Ghats headwater origin',
    upstream_source: 'Wayanad Catchments & Banasura Sagar (+0h origin)',
    downstream_target: 'Biligundlu Gauge (+5h travel lag) → Mettur Dam (+8h lag)',
    transit_detail: 'Surges generated by rapid spillway sluice releases propagate down the Kabini tributary into the Cauvery confluence at Tirumakudalu Narasipura within 2–3 hours, entering Biligundlu in ~5 hours.',
    inundation_risk: 'Backwater submergence in low-lying riparian tracts of H.D. Kote taluk and downstream agrarian fields along the Kabini riverbanks during peak monsoon spills.',
  },
  {
    id: 'KRS',
    name: 'KRS (Krishna Raja Sagara)',
    type: 'reservoir',
    reach: 'Upper Cauvery',
    travel_hrs: 2,
    desc: 'Primary Karnataka storage hub',
    upstream_source: 'Upper Cauvery, Harangi & Hemavathi inflows (+0h to +2h)',
    downstream_target: 'Mekedatu Gorge → Biligundlu (+3h travel lag) → Mettur (+6h lag)',
    transit_detail: 'Controlled discharges through KRS crest gates traverse the Mysore plateau, pass Srirangapatna and plunge through Mekedatu gorge, arriving at Biligundlu gauge in ~3 hours and Mettur reservoir in ~6 hours.',
    inundation_risk: 'High-velocity flow scour along Srirangapatna island, submerging ancient river ghats and low-level road bridges when discharge exceeds 80,000 cusecs.',
  },
  {
    id: 'BILIGUNDLU',
    name: 'Biligundlu Gauge',
    type: 'gauge',
    reach: 'Inter-State Border',
    travel_hrs: 5,
    desc: 'Central Water Commission border reference gauge',
    upstream_source: 'Combined releases from Kabini (+5h lag) & KRS (+3h lag)',
    downstream_target: 'Hogenakkal Gorge → Mettur Dam Backwaters (+3h travel lag)',
    transit_detail: 'Inter-state boundary reference gauge measuring consolidated Karnataka releases. Flood hydrographs recorded here reach Hogenakkal Falls in ~1 hour and propagate into the head of Mettur reservoir backwaters in ~3 hours.',
    inundation_risk: 'Gorge constriction inundation at Hogenakkal tourist viewpoints and riverside settlements; serves as the critical early-warning threshold for Mettur Dam floodgate operations.',
  },
  {
    id: 'METTUR_DAM',
    name: 'Mettur Dam (Stanley)',
    type: 'reservoir',
    reach: 'Middle Reach',
    travel_hrs: 8,
    desc: 'Major Tamil Nadu multi-purpose reservoir',
    upstream_source: 'Biligundlu Border inflow (+3h lag; +8h cumulative from headwaters)',
    downstream_target: 'Bhavani River Confluence (+3h) → Erode Gauge (+4h travel lag)',
    transit_detail: 'Acts as Tamil Nadu’s chief hydrodynamic flood buffer (93.47 TMC capacity). Once full (level 120 ft), surplus discharges via the 16-vent Ellis surplus regulator reach Erode in ~4 hours, Karur in ~10 hours, and Trichy in ~15 hours.',
    inundation_risk: 'Discharges exceeding 100,000 cusecs cause immediate bank overtopping in low-lying riverside colonies in Bhavani, Kumarapalayam, Pallipalayam, and Erode.',
  },
  {
    id: 'ERODE',
    name: 'Erode Gauge',
    type: 'gauge',
    reach: 'Bhavani Confluence',
    travel_hrs: 12,
    desc: 'Downstream of Bhavani confluence',
    upstream_source: 'Mettur Dam discharge (+4h lag) + Bhavanisagar confluence (+1–2h)',
    downstream_target: 'Kodumudi Gauge (+3h travel lag) → Karur Gauge (+6h lag)',
    transit_detail: 'Situated downstream of the critical Cauvery–Bhavani confluence. Peak hydrograph stages reflect compound surges from Mettur releases and tributary inflows from Bhavanisagar, transiting downstream to Kodumudi in ~3 hours.',
    inundation_risk: 'Backwater swelling at the Bhavani Sangameshwarar temple zone and inundation of municipal bypass roads and weavers’ quarters in Pallipalayam and Cauvery RS.',
  },
  {
    id: 'KODUMUDI',
    name: 'Kodumudi Gauge',
    type: 'gauge',
    reach: 'Middle Cauvery',
    travel_hrs: 15,
    desc: 'Mid-basin alluvial floodway',
    upstream_source: 'Erode composite flood wave (+3h lag; +7h from Mettur Dam)',
    downstream_target: 'Noyyal River Confluence → Karur Gauge (+3h travel lag)',
    transit_detail: 'Broad alluvial riverbed reach with natural lateral attenuation slowing the flood wave velocity slightly. Discharges from Kodumudi traverse the Noyyal junction, arriving at Karur within ~3 hours.',
    inundation_risk: 'Submergence of riparian agricultural lands, banana plantations, and temple bathing ghats along the river margin during sustained high discharges.',
  },
  {
    id: 'KARUR',
    name: 'Karur Gauge',
    type: 'gauge',
    reach: 'Amaravathi Confluence',
    travel_hrs: 18,
    desc: 'Amaravathi tributary junction',
    upstream_source: 'Kodumudi reach (+3h lag) + Amaravathi river confluence (+1–2h)',
    downstream_target: 'Mayanur Barrage → Musiri Gauge (+3h travel lag) → Trichy (+5h lag)',
    transit_detail: 'Receives composite discharge from the main Cauvery trunk and Amaravathi river basin (+18h total routing lag from Karnataka headwaters). Regulated downstream via Mayanur Barrage, waves reach Musiri in ~3 hours.',
    inundation_risk: 'Flash flooding risk at Amaravathi confluence; Mayanur barrage backwaters flood low-lying fields in Manmangalam and Vangal agrarian belts.',
  },
  {
    id: 'MUSIRI',
    name: 'Musiri Gauge',
    type: 'gauge',
    reach: 'Lower Reach',
    travel_hrs: 21,
    desc: 'Upper delta approach',
    upstream_source: 'Karur / Mayanur Barrage outflow (+3h lag; +13h from Mettur Dam)',
    downstream_target: 'Upper Anicut (Mukkombu) Bifurcation (+2h travel lag) → Trichy (+2–3h lag)',
    transit_detail: 'Upper delta approach where river channel flattens out significantly. Flood waves entering Musiri require approximately 2 hours to reach the hydraulic control structures at Upper Anicut (Mukkombu).',
    inundation_risk: 'Erosion of sandy bunds and flooding of island villages and agricultural tracts between Musiri and Kulithalai bridges.',
  },
  {
    id: 'TRICHY_UPPER',
    name: 'Trichy Upper Gauge',
    type: 'gauge',
    reach: 'Delta Entrance',
    travel_hrs: 23,
    desc: 'Kollidam branch regulator bifurcation',
    upstream_source: 'Musiri reach (+2h lag; +15h from Mettur; +23h from headwaters)',
    downstream_target: 'Bifurcation: Kollidam flood carrier (to sea) & Cauvery branch to Grand Anicut (+2–3h lag)',
    transit_detail: 'Critical hydraulic junction at Upper Anicut (Mukkombu). Excess flood discharges are diverted into the wide Kollidam river channel to shield Trichy city and delta farmlands. Residual flow reaches Grand Anicut (Kallanai) in ~2 hours.',
    inundation_risk: 'If Kollidam regulator shutters cannot discharge peak volume, backwaters threaten Srirangam island, Tiruchirappalli city banks, and low-lying bypass corridors.',
  },
  {
    id: 'GRAND_ANICUT',
    name: 'Grand Anicut (Kallanai)',
    type: 'gauge',
    reach: 'Delta Terminus',
    travel_hrs: 26,
    desc: 'Historic 4-channel delta diversion regulator',
    upstream_source: 'Trichy Upper / Mukkombu branch (+2h lag; +26h cumulative transit from Western Ghats)',
    downstream_target: 'Delta distribution: Cauvery, Vennar, Grand Anicut Canal, and Lower Kollidam',
    transit_detail: 'The ancient terminus of the upstream river routing corridor. Cumulative flood surge transit time from Kabini/KRS is ~26 hours. Flows are distributed across 4 distinct canal networks for irrigation and sea discharge.',
    inundation_risk: 'Tail-end delta flood hazard. Surges exceeding canal capacity cause breach of earthen bunds across Thanjavur, Tiruvarur, and Nagapattinam paddy floodplains.',
  },
];


export default function FloodRoutingPage() {
  const [dashboardData, setDashboardData] = useState<any>(null);
  const [selectedNodeId, setSelectedNodeId] = useState<string>('METTUR_DAM');
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [hasError, setHasError] = useState<boolean>(false);

  const loadData = async () => {
    try {
      setIsLoading(true);
      setHasError(false);
      await api.login();
      const dash = await api.getDashboard();
      setDashboardData(dash);
    } catch (err) {
      console.error('Failed to load routing data:', err);
      setHasError(true);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const stations = dashboardData?.stations || [];
  const reservoirs = dashboardData?.reservoirs || [];

  // Merge topological routing nodes with live telemetry
  const networkNodes = useMemo(() => {
    return ROUTING_NODES_CONFIG.map((cfg) => {
      const station = stations.find((s: any) => s.id === cfg.id || s.id === cfg.id.replace('_DAM', ''));
      const reservoir = reservoirs.find((r: any) => r.id === cfg.id || r.id === cfg.id.replace('_DAM', ''));

      const waterLevel = station?.water_level || null;
      const dangerLevel = station?.danger_level || null;
      const riskLevel = station?.risk_level || 'Safe';
      const storagePct = reservoir?.storage_pct || null;
      const discharge = station?.discharge || reservoir?.release_cumecs || null;

      return {
        ...cfg,
        water_level: waterLevel,
        danger_level: dangerLevel,
        risk_level: riskLevel,
        storage_pct: storagePct,
        discharge: discharge,
      };
    });
  }, [stations, reservoirs]);

  const selectedNode = useMemo(() => {
    return networkNodes.find((n) => n.id === selectedNodeId) || networkNodes[3];
  }, [networkNodes, selectedNodeId]);

  const nodesNeedingAttention = useMemo(() => {
    return networkNodes.filter((n) => {
      const r = (n.risk_level || '').toLowerCase();
      return r.includes('danger') || r.includes('warn') || r.includes('severe');
    });
  }, [networkNodes]);

  if (isLoading) {
    return (
      <AppLayout>
        <LoadingSkeleton rows={6} height={90} />
      </AppLayout>
    );
  }

  if (hasError || !dashboardData) {
    return (
      <AppLayout>
        <ErrorBanner onRetry={loadData} />
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        {/* Header Overview */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <h2 style={{ fontSize: '1.2rem', fontWeight: 600, color: '#f8fafc', margin: 0 }}>
              Cauvery River Network Flood Propagation
            </h2>
            <p style={{ fontSize: '0.8rem', color: '#94a3b8', margin: '2px 0 0' }}>
              Sequential topological flow from headwater reservoirs down to the Cauvery Delta (Grand Anicut)
            </p>
          </div>

          {nodesNeedingAttention.length > 0 ? (
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                backgroundColor: 'rgba(245, 158, 11, 0.1)',
                border: '1px solid rgba(245, 158, 11, 0.25)',
                padding: '6px 12px',
                borderRadius: 6,
                fontSize: '0.78rem',
                color: '#f59e0b',
                fontWeight: 600,
              }}
            >
              <AlertTriangle size={14} />
              <span>{nodesNeedingAttention.length} node(s) requiring attention along routing path</span>
            </div>
          ) : (
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                backgroundColor: 'rgba(16, 185, 129, 0.08)',
                border: '1px solid rgba(16, 185, 129, 0.2)',
                padding: '6px 12px',
                borderRadius: 6,
                fontSize: '0.78rem',
                color: '#10b981',
              }}
            >
              <CheckCircle size={14} />
              <span>All reaches routing within normal flow capacities</span>
            </div>
          )}
        </div>

        {/* 2-Column: Flow Chain (Left) + Reach Detail (Right) */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'minmax(0, 1.4fr) minmax(0, 1fr)',
            gap: 20,
          }}
        >
          {/* LEFT: Upstream to Downstream Flow Schematic */}
          <div className="card" style={{ padding: '18px 20px' }}>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: 16,
                paddingBottom: 10,
                borderBottom: '1px solid var(--border-subtle)',
              }}
            >
              <div className="card-title">
                <GitBranch size={15} color="#0ea5e9" />
                <span>Upstream → Downstream River Reach Topology</span>
              </div>
              <span style={{ fontSize: '0.72rem', color: '#64748b' }}>
                Estimated Travel Lag (Hours)
              </span>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {networkNodes.map((node, index) => {
                const isSelected = node.id === selectedNodeId;
                const isLast = index === networkNodes.length - 1;

                return (
                  <React.Fragment key={node.id}>
                    <div
                      onClick={() => setSelectedNodeId(node.id)}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        padding: '10px 14px',
                        borderRadius: 6,
                        backgroundColor: isSelected
                          ? 'rgba(14, 165, 233, 0.12)'
                          : 'var(--bg-surface)',
                        border: `1px solid ${
                          isSelected ? 'rgba(14, 165, 233, 0.35)' : 'var(--border-subtle)'
                        }`,
                        cursor: 'pointer',
                        transition: 'all 0.12s ease',
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                        <div
                          style={{
                            width: 28,
                            height: 28,
                            borderRadius: 4,
                            backgroundColor: node.type === 'reservoir' ? 'rgba(14, 165, 233, 0.15)' : 'rgba(255, 255, 255, 0.05)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            color: node.type === 'reservoir' ? '#38bdf8' : '#94a3b8',
                          }}
                        >
                          {node.type === 'reservoir' ? <Droplets size={14} /> : <Radio size={14} />}
                        </div>

                        <div>
                          <div style={{ fontSize: '0.84rem', fontWeight: 600, color: '#f8fafc' }}>
                            {node.name}
                          </div>
                          <div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>
                            {node.reach} · +{node.travel_hrs}h routing lag
                          </div>
                        </div>
                      </div>

                      <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
                        {node.water_level != null && (
                          <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: '#f8fafc' }}>
                            {Number(node.water_level).toFixed(1)} ft
                          </span>
                        )}
                        {node.storage_pct != null && (
                          <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.82rem', color: '#38bdf8' }}>
                            {Math.round(node.storage_pct)}% cap
                          </span>
                        )}
                        <RiskBadge level={node.risk_level} size="sm" />
                      </div>
                    </div>

                    {!isLast && (
                      <div
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          padding: '2px 0',
                          color: '#0ea5e9',
                          opacity: 0.6,
                        }}
                      >
                        <ArrowDown size={14} />
                      </div>
                    )}
                  </React.Fragment>
                );
              })}
            </div>
          </div>

          {/* RIGHT: Selected Reach Routing Detail */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            <div className="card">
              <div className="card-header">
                <div>
                  <div className="card-title">
                    <span>{selectedNode.name}</span>
                  </div>
                  <div style={{ fontSize: '0.72rem', color: '#94a3b8', marginTop: 2 }}>
                    Reach: {selectedNode.reach}
                  </div>
                </div>
                <RiskBadge level={selectedNode.risk_level} />
              </div>

              <div className="card-body" style={{ padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 14 }}>
                <p style={{ fontSize: '0.82rem', color: '#94a3b8', margin: 0 }}>
                  {selectedNode.desc}
                </p>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                  <div style={{ backgroundColor: 'var(--bg-surface)', padding: 12, borderRadius: 6, border: '1px solid var(--border-subtle)' }}>
                    <div style={{ fontSize: '0.7rem', color: '#94a3b8', textTransform: 'uppercase', fontWeight: 600 }}>
                      Travel Lag From Origin
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.4rem', fontWeight: 700, color: '#38bdf8', marginTop: 4 }}>
                      +{selectedNode.travel_hrs}h
                    </div>
                    <div style={{ fontSize: '0.7rem', color: '#64748b' }}>
                      Hydrodynamic flood wave transit time
                    </div>
                  </div>

                  <div style={{ backgroundColor: 'var(--bg-surface)', padding: 12, borderRadius: 6, border: '1px solid var(--border-subtle)' }}>
                    <div style={{ fontSize: '0.7rem', color: '#94a3b8', textTransform: 'uppercase', fontWeight: 600 }}>
                      Current Level
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.4rem', fontWeight: 700, color: '#f8fafc', marginTop: 4 }}>
                      {selectedNode.water_level != null ? `${Number(selectedNode.water_level).toFixed(2)} ft` : 'N/A'}
                    </div>
                    <div style={{ fontSize: '0.7rem', color: '#64748b' }}>
                      {selectedNode.danger_level != null ? `Danger: ${Number(selectedNode.danger_level).toFixed(1)} ft` : 'Storage node'}
                    </div>
                  </div>
                </div>

                {selectedNode.storage_pct != null && (
                  <div style={{ backgroundColor: 'var(--bg-surface)', padding: 12, borderRadius: 6, border: '1px solid var(--border-subtle)' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.76rem', marginBottom: 6 }}>
                      <span style={{ color: '#94a3b8' }}>Reservoir Storage Fill:</span>
                      <strong style={{ color: '#38bdf8' }}>{selectedNode.storage_pct.toFixed(1)}%</strong>
                    </div>
                    <div style={{ width: '100%', height: 6, backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 3, overflow: 'hidden' }}>
                      <div
                        style={{
                          height: '100%',
                          width: `${Math.min(100, selectedNode.storage_pct)}%`,
                          backgroundColor: selectedNode.storage_pct > 85 ? '#ef4444' : selectedNode.storage_pct > 70 ? '#f59e0b' : '#0ea5e9',
                        }}
                      />
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Station-Specific Transit & Inundation Propagation */}
            <div className="card" style={{ padding: '16px 18px', display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                  <Clock size={15} color="#0ea5e9" />
                  <span style={{ fontSize: '0.82rem', fontWeight: 600, color: '#f8fafc' }}>
                    Transit & Inundation Propagation
                  </span>
                </div>
                <span
                  style={{
                    fontSize: '0.68rem',
                    padding: '2px 8px',
                    borderRadius: 10,
                    backgroundColor: 'rgba(14, 165, 233, 0.12)',
                    color: '#38bdf8',
                    border: '1px solid rgba(14, 165, 233, 0.3)',
                    fontWeight: 600,
                  }}
                >
                  +{selectedNode.travel_hrs}h from origin
                </span>
              </div>

              {/* Station Specific Hydrodynamic Dynamics */}
              <div>
                <div style={{ fontSize: '0.72rem', color: '#64748b', textTransform: 'uppercase', fontWeight: 600, marginBottom: 4 }}>
                  Station Reach Hydrodynamics &bull; {selectedNode.name}
                </div>
                <p style={{ fontSize: '0.76rem', color: '#cbd5e1', lineHeight: 1.55, margin: 0 }}>
                  {selectedNode.transit_detail}
                </p>
              </div>

              {/* Inflow & Outflow propagation corridor */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: 8 }}>
                <div style={{ backgroundColor: 'var(--bg-surface)', padding: '9px 12px', borderRadius: 6, border: '1px solid var(--border-subtle)' }}>
                  <div style={{ fontSize: '0.68rem', color: '#94a3b8', textTransform: 'uppercase', fontWeight: 600, display: 'flex', alignItems: 'center', gap: 4, marginBottom: 3 }}>
                    <GitBranch size={12} color="#0ea5e9" /> Upstream Feeder & Inflow Lag
                  </div>
                  <div style={{ fontSize: '0.74rem', color: '#e2e8f0', lineHeight: 1.4 }}>
                    {selectedNode.upstream_source}
                  </div>
                </div>

                <div style={{ backgroundColor: 'var(--bg-surface)', padding: '9px 12px', borderRadius: 6, border: '1px solid var(--border-subtle)' }}>
                  <div style={{ fontSize: '0.68rem', color: '#94a3b8', textTransform: 'uppercase', fontWeight: 600, display: 'flex', alignItems: 'center', gap: 4, marginBottom: 3 }}>
                    <ArrowDown size={12} color="#38bdf8" /> Downstream Wave Target & Transit
                  </div>
                  <div style={{ fontSize: '0.74rem', color: '#e2e8f0', lineHeight: 1.4 }}>
                    {selectedNode.downstream_target}
                  </div>
                </div>
              </div>

              {/* Inundation Risk & Floodplain Impact */}
              <div
                style={{
                  backgroundColor: 'rgba(239, 68, 68, 0.06)',
                  border: '1px solid rgba(239, 68, 68, 0.25)',
                  borderRadius: 6,
                  padding: '10px 12px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 4 }}>
                  <AlertTriangle size={13} color="#f87171" />
                  <span style={{ fontSize: '0.7rem', fontWeight: 600, color: '#fca5a5', textTransform: 'uppercase', letterSpacing: '0.03em' }}>
                    Local Inundation & Floodplain Vulnerability
                  </span>
                </div>
                <p style={{ fontSize: '0.74rem', color: '#e2e8f0', lineHeight: 1.45, margin: 0 }}>
                  {selectedNode.inundation_risk}
                </p>
              </div>

              {/* Basin Corridor Reference */}
              <div
                style={{
                  paddingTop: 8,
                  borderTop: '1px solid rgba(255,255,255,0.06)',
                  fontSize: '0.68rem',
                  color: '#64748b',
                  lineHeight: 1.4,
                }}
              >
                <strong style={{ color: '#94a3b8' }}>Basin-Wide Corridor:</strong> Headwaters (0h) &rarr; Mettur Dam (+8h) &rarr; Karur (+18h) &rarr; Trichy / Grand Anicut (+23–26h)
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
